name: Flask CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: docker build -t ghcr.io/syzquierdo/flask-cicd-pipeline:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/syzquierdo/flask-cicd-pipeline:latest
          format: table
          exit-code: 0

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u syzquierdo --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/syzquierdo/flask-cicd-pipeline:latest